In [3]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

In [19]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

In [4]:
df = pd.read_csv("diabetes.csv")

In [5]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [6]:
df.tail()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [7]:
df.shape

(768, 9)

In [8]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [10]:
df['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [11]:
X = df.drop(columns = ["Outcome"] , axis=1)
Y = df["Outcome"]

In [12]:
print(Y)

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [13]:
print(X)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6
1              1       85             66             29        0  26.6
2              8      183             64              0        0  23.3
3              1       89             66             23       94  28.1
4              0      137             40             35      168  43.1
..           ...      ...            ...            ...      ...   ...
763           10      101             76             48      180  32.9
764            2      122             70             27        0  36.8
765            5      121             72             23      112  26.2
766            1      126             60              0        0  30.1
767            1       93             70             31        0  30.4

     DiabetesPedigreeFunction  Age
0                       0.627   50
1                       0.351   31
2                       0.672   32
3                       0.167   21
4                       2.288   33
..                        ...  ...
763                     0.171   63
764                     0.340   27
765                     0.245   30
766                     0.349   47
767                     0.315   23

[768 rows x 8 columns]

In [15]:
X.std()

Pregnancies                   3.369578
Glucose                      31.972618
BloodPressure                19.355807
SkinThickness                15.952218
Insulin                     115.244002
BMI                           7.884160
DiabetesPedigreeFunction      0.331329
Age                          11.760232
dtype: float64

In [16]:
scaler = StandardScaler()
scaler.fit(X)
stand_x = scaler.transform(X)

In [17]:
stand_x.std()

1.0

In [21]:
X = np.asarray(stand_x)
Y = np.asarray(Y)

In [36]:
grid = {
   
    'C': [1,5,10,20],
    'kernel': ['rbf', 'linear', 'sigmoid', 'poly']
}

In [37]:
model = SVC()
classifier = GridSearchCV(model ,grid , cv =5)

In [38]:
classifier.fit(X,Y)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [1, 5, 10, 20],
                         'kernel': ['rbf', 'linear', 'sigmoid', 'poly']})

In [39]:
classifier.cv_results_

{'mean_fit_time': array([0.00582886, 0.00397196, 0.00302978, 0.00224695, 0.00259609,
        0.00790653, 0.00239139, 0.00401883, 0.00334678, 0.01128359,
        0.00211368, 0.00641055, 0.00379024, 0.01885247, 0.0020278 ,
        0.00984073]),
 'std_fit_time': array([2.89631523e-03, 1.61446570e-04, 2.91142235e-04, 9.98525473e-05,
        4.15465564e-05, 8.40493167e-04, 2.27117163e-04, 4.07631668e-04,
        2.06186096e-04, 1.33824376e-03, 1.75756161e-04, 7.97521935e-04,
        3.73563494e-05, 2.08639541e-03, 1.11140544e-04, 2.05339717e-03]),
 'mean_score_time': array([0.00247903, 0.00055103, 0.00066795, 0.0003922 , 0.00103769,
        0.00042439, 0.00058479, 0.00042725, 0.00105743, 0.00037165,
        0.0004705 , 0.0003799 , 0.00097804, 0.00037055, 0.00045986,
        0.00037928]),
 'std_score_time': array([1.25208433e-03, 3.79609699e-05, 4.49011502e-05, 2.16381116e-05,
        3.22542890e-05, 4.39722981e-05, 1.18770306e-04, 4.84512075e-05,
        1.13586114e-04, 7.50833065e-06, 7.15827713e-06, 9.61935502e-06,
        2.49388113e-05, 8.37035987e-06, 9.50498060e-06, 1.09136349e-05]),
 'param_C': masked_array(data=[1, 1, 1, 1, 5, 5, 5, 5, 10, 10, 10, 10, 20, 20, 20, 20],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'sigmoid', 'poly', 'rbf', 'linear',
                    'sigmoid', 'poly', 'rbf', 'linear', 'sigmoid', 'poly',
                    'rbf', 'linear', 'sigmoid', 'poly'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 1, 'kernel': 'sigmoid'},
  {'C': 1, 'kernel': 'poly'},
  {'C': 5, 'kernel': 'rbf'},
  {'C': 5, 'kernel': 'linear'},
  {'C': 5, 'kernel': 'sigmoid'},
  {'C': 5, 'kernel': 'poly'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'sigmoid'},
  {'C': 10, 'kernel': 'poly'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'sigmoid'},
  {'C': 20, 'kernel': 'poly'}],
 'split0_test_score': array([0.76623377, 0.76623377, 0.68181818, 0.74025974, 0.74675325,
        0.76623377, 0.65584416, 0.75324675, 0.74025974, 0.76623377,
        0.70779221, 0.73376623, 0.71428571, 0.76623377, 0.68831169,
        0.71428571]),
 'split1_test_score': array([0.75324675, 0.75974026, 0.7012987 , 0.77272727, 0.75324675,
        0.75974026, 0.68831169, 0.76623377, 0.74675325, 0.75974026,
        0.68181818, 0.74675325, 0.70779221, 0.75974026, 0.65584416,
        0.74675325]),
 'split2_test_score': array([0.74675325, 0.75974026, 0.70779221, 0.72077922, 0.74675325,
        0.75974026, 0.70779221, 0.74025974, 0.75974026, 0.75974026,
        0.7012987 , 0.72727273, 0.74025974, 0.75974026, 0.70779221,
        0.71428571]),
 'split3_test_score': array([0.81045752, 0.81699346, 0.71895425, 0.76470588, 0.83006536,
        0.81699346, 0.70588235, 0.77777778, 0.79084967, 0.81699346,
        0.7124183 , 0.75816993, 0.76470588, 0.81699346, 0.69934641,
        0.75163399]),
 'split4_test_score': array([0.77777778, 0.76470588, 0.7254902 , 0.74509804, 0.81045752,
        0.76470588, 0.70588235, 0.75816993, 0.81699346, 0.76470588,
        0.68627451, 0.74509804, 0.80392157, 0.76470588, 0.67320261,
        0.75163399]),
 'mean_test_score': array([0.77089381, 0.77348273, 0.70707071, 0.74871403, 0.77745522,
        0.77348273, 0.69274255, 0.75913759, 0.77091928, 0.77348273,
        0.69792038, 0.74221204, 0.74619302, 0.77348273, 0.68489941,
        0.73571853]),
 'std_test_score': array([0.02248812, 0.02191107, 0.01517908, 0.01842433, 0.03557598,
        0.02191107, 0.01976322, 0.0125684 , 0.02887569, 0.02191107,
        0.01194958, 0.01075287, 0.03522276, 0.02191107, 0.01857666,
        0.01759034]),
 'rank_test_score': array([ 7,  2, 13,  9,  1,  2, 15,  8,  6,  2, 14, 11, 10,  2, 16, 12],
       dtype=int32)}

In [40]:
print("best parametrs = ",classifier.best_params_ )

best parametrs =  {'C': 5, 'kernel': 'rbf'}

In [41]:
print("highest accuracy  = ", classifier.best_score_)

highest accuracy  =  0.777455224514048

In [42]:
df_ = pd.DataFrame(classifier.cv_results_)

In [43]:
df_.head()

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.005829,0.002896,0.002479,0.001252,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.766234,0.753247,0.746753,0.810458,0.777778,0.770894,0.022488,7
1,0.003972,0.000161,0.000551,0.000038,1,linear,"{'C': 1, 'kernel': 'linear'}",0.766234,0.759740,0.759740,0.816993,0.764706,0.773483,0.021911,2
2,0.003030,0.000291,0.000668,0.000045,1,sigmoid,"{'C': 1, 'kernel': 'sigmoid'}",0.681818,0.701299,0.707792,0.718954,0.725490,0.707071,0.015179,13
3,0.002247,0.000100,0.000392,0.000022,1,poly,"{'C': 1, 'kernel': 'poly'}",0.740260,0.772727,0.720779,0.764706,0.745098,0.748714,0.018424,9
4,0.002596,0.000042,0.001038,0.000032,5,rbf,"{'C': 5, 'kernel': 'rbf'}",0.746753,0.753247,0.746753,0.830065,0.810458,0.777455,0.035576,1

In [48]:

grid_search_results = df_[['param_C', 'param_kernel', 'mean_test_score']]

In [49]:
grid_search_results

    param_C param_kernel  mean_test_score
0         1          rbf         0.770894
1         1       linear         0.773483
2         1      sigmoid         0.707071
3         1         poly         0.748714
4         5          rbf         0.777455
5         5       linear         0.773483
6         5      sigmoid         0.692743
7         5         poly         0.759138
8        10          rbf         0.770919
9        10       linear         0.773483
10       10      sigmoid         0.697920
11       10         poly         0.742212
12       20          rbf         0.746193
13       20       linear         0.773483
14       20      sigmoid         0.684899
15       20         poly         0.735719

In [50]:
classifier = RandomizedSearchCV(model ,grid , cv =5)

In [51]:
classifier.fit(X,Y)

RandomizedSearchCV(cv=5, estimator=SVC(),
                   param_distributions={'C': [1, 5, 10, 20],
                                        'kernel': ['rbf', 'linear', 'sigmoid',
                                                   'poly']})

In [52]:
df2 = pd.DataFrame(classifier.cv_results_)

In [53]:
random_search_results = df2[['param_C', 'param_kernel', 'mean_test_score']]

In [54]:
random_search_results

   param_C param_kernel  mean_test_score
0        1          rbf         0.770894
1        5      sigmoid         0.692743
2        5       linear         0.773483
3       10         poly         0.742212
4        5          rbf         0.777455
5       20         poly         0.735719
6       20       linear         0.773483
7       10          rbf         0.770919
8       10       linear         0.773483
9        5         poly         0.759138

In [55]:
print("best parametrs = ",classifier.best_params_ )

best parametrs =  {'kernel': 'rbf', 'C': 5}